#!/bin/sh

base=roadmaster-core

case "$1" in
  start)
                nohup /usr/bin/$base &
        ;;
  stop)
        pid=`/bin/pidof $base`
        if [ -n "$pid" ]; then
                kill -9 $pid
        fi
        ;;
esac

exit 0
